### ISSUE TITLE
Create base clap structure

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/makectl#1]
Add `clap` as a dependency and create the basic struct for clap to turn this in to a CLI app

**Comment by HirotoShioi** [comment]
Is it okay if I work on this? Also, what are the commands you're expecting to be introduced in this PR?
Currently, have `add` as a subcommand which takes multiple `template` arguments (e.g. `makectl add --template=one --template=two`)

**Comment by luizdepra** [comment]
Have you considered to use [`structopt`](https://crates.io/crates/structopt) instead?

**Comment by rochacbruno** [comment]
@luizdepra no objection on using it, I have used Clap once, so I already know how it works. BUt if you are willing to send a PR with structopt I am ok to learn it.
